// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

// Protobuf Java Version: 3.25.1
package org.matrix.game.proto.c2s;

public interface EnterGameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnterGame)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 playerId = 1;</code>
   * @return The playerId.
   */
  long getPlayerId();
}
