// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

// Protobuf Java Version: 3.25.1
package org.matrix.game.proto.c2s;

/**
 * Protobuf type {@code GameResp}
 */
public final class GameResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GameResp)
    GameRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GameResp.newBuilder() to construct.
  private GameResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GameResp() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GameResp();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.matrix.game.proto.c2s.C2SMsg.internal_static_GameResp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.matrix.game.proto.c2s.C2SMsg.internal_static_GameResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.matrix.game.proto.c2s.GameResp.class, org.matrix.game.proto.c2s.GameResp.Builder.class);
  }

  private int payloadCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object payload_;
  public enum PayloadCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    ENTERGAMERT(1001),
    STRINGMSGRT(2001),
    NUMBERMSGRT(2002),
    PAYLOAD_NOT_SET(0);
    private final int value;
    private PayloadCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PayloadCase valueOf(int value) {
      return forNumber(value);
    }

    public static PayloadCase forNumber(int value) {
      switch (value) {
        case 1001: return ENTERGAMERT;
        case 2001: return STRINGMSGRT;
        case 2002: return NUMBERMSGRT;
        case 0: return PAYLOAD_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PayloadCase
  getPayloadCase() {
    return PayloadCase.forNumber(
        payloadCase_);
  }

  public static final int CODE_FIELD_NUMBER = 1;
  private int code_ = 0;
  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  @java.lang.Override
  public int getCode() {
    return code_;
  }

  public static final int ENTERGAMERT_FIELD_NUMBER = 1001;
  /**
   * <pre>
   * 登录
   * </pre>
   *
   * <code>.EnterGameRt enterGameRt = 1001;</code>
   * @return Whether the enterGameRt field is set.
   */
  @java.lang.Override
  public boolean hasEnterGameRt() {
    return payloadCase_ == 1001;
  }
  /**
   * <pre>
   * 登录
   * </pre>
   *
   * <code>.EnterGameRt enterGameRt = 1001;</code>
   * @return The enterGameRt.
   */
  @java.lang.Override
  public org.matrix.game.proto.c2s.EnterGameRt getEnterGameRt() {
    if (payloadCase_ == 1001) {
       return (org.matrix.game.proto.c2s.EnterGameRt) payload_;
    }
    return org.matrix.game.proto.c2s.EnterGameRt.getDefaultInstance();
  }
  /**
   * <pre>
   * 登录
   * </pre>
   *
   * <code>.EnterGameRt enterGameRt = 1001;</code>
   */
  @java.lang.Override
  public org.matrix.game.proto.c2s.EnterGameRtOrBuilder getEnterGameRtOrBuilder() {
    if (payloadCase_ == 1001) {
       return (org.matrix.game.proto.c2s.EnterGameRt) payload_;
    }
    return org.matrix.game.proto.c2s.EnterGameRt.getDefaultInstance();
  }

  public static final int STRINGMSGRT_FIELD_NUMBER = 2001;
  /**
   * <pre>
   * 测试
   * </pre>
   *
   * <code>.StringMsgRt stringMsgRt = 2001;</code>
   * @return Whether the stringMsgRt field is set.
   */
  @java.lang.Override
  public boolean hasStringMsgRt() {
    return payloadCase_ == 2001;
  }
  /**
   * <pre>
   * 测试
   * </pre>
   *
   * <code>.StringMsgRt stringMsgRt = 2001;</code>
   * @return The stringMsgRt.
   */
  @java.lang.Override
  public org.matrix.game.proto.c2s.StringMsgRt getStringMsgRt() {
    if (payloadCase_ == 2001) {
       return (org.matrix.game.proto.c2s.StringMsgRt) payload_;
    }
    return org.matrix.game.proto.c2s.StringMsgRt.getDefaultInstance();
  }
  /**
   * <pre>
   * 测试
   * </pre>
   *
   * <code>.StringMsgRt stringMsgRt = 2001;</code>
   */
  @java.lang.Override
  public org.matrix.game.proto.c2s.StringMsgRtOrBuilder getStringMsgRtOrBuilder() {
    if (payloadCase_ == 2001) {
       return (org.matrix.game.proto.c2s.StringMsgRt) payload_;
    }
    return org.matrix.game.proto.c2s.StringMsgRt.getDefaultInstance();
  }

  public static final int NUMBERMSGRT_FIELD_NUMBER = 2002;
  /**
   * <code>.NumberMsgRt numberMsgRt = 2002;</code>
   * @return Whether the numberMsgRt field is set.
   */
  @java.lang.Override
  public boolean hasNumberMsgRt() {
    return payloadCase_ == 2002;
  }
  /**
   * <code>.NumberMsgRt numberMsgRt = 2002;</code>
   * @return The numberMsgRt.
   */
  @java.lang.Override
  public org.matrix.game.proto.c2s.NumberMsgRt getNumberMsgRt() {
    if (payloadCase_ == 2002) {
       return (org.matrix.game.proto.c2s.NumberMsgRt) payload_;
    }
    return org.matrix.game.proto.c2s.NumberMsgRt.getDefaultInstance();
  }
  /**
   * <code>.NumberMsgRt numberMsgRt = 2002;</code>
   */
  @java.lang.Override
  public org.matrix.game.proto.c2s.NumberMsgRtOrBuilder getNumberMsgRtOrBuilder() {
    if (payloadCase_ == 2002) {
       return (org.matrix.game.proto.c2s.NumberMsgRt) payload_;
    }
    return org.matrix.game.proto.c2s.NumberMsgRt.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (code_ != 0) {
      output.writeInt32(1, code_);
    }
    if (payloadCase_ == 1001) {
      output.writeMessage(1001, (org.matrix.game.proto.c2s.EnterGameRt) payload_);
    }
    if (payloadCase_ == 2001) {
      output.writeMessage(2001, (org.matrix.game.proto.c2s.StringMsgRt) payload_);
    }
    if (payloadCase_ == 2002) {
      output.writeMessage(2002, (org.matrix.game.proto.c2s.NumberMsgRt) payload_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (code_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, code_);
    }
    if (payloadCase_ == 1001) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1001, (org.matrix.game.proto.c2s.EnterGameRt) payload_);
    }
    if (payloadCase_ == 2001) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2001, (org.matrix.game.proto.c2s.StringMsgRt) payload_);
    }
    if (payloadCase_ == 2002) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2002, (org.matrix.game.proto.c2s.NumberMsgRt) payload_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.matrix.game.proto.c2s.GameResp)) {
      return super.equals(obj);
    }
    org.matrix.game.proto.c2s.GameResp other = (org.matrix.game.proto.c2s.GameResp) obj;

    if (getCode()
        != other.getCode()) return false;
    if (!getPayloadCase().equals(other.getPayloadCase())) return false;
    switch (payloadCase_) {
      case 1001:
        if (!getEnterGameRt()
            .equals(other.getEnterGameRt())) return false;
        break;
      case 2001:
        if (!getStringMsgRt()
            .equals(other.getStringMsgRt())) return false;
        break;
      case 2002:
        if (!getNumberMsgRt()
            .equals(other.getNumberMsgRt())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode();
    switch (payloadCase_) {
      case 1001:
        hash = (37 * hash) + ENTERGAMERT_FIELD_NUMBER;
        hash = (53 * hash) + getEnterGameRt().hashCode();
        break;
      case 2001:
        hash = (37 * hash) + STRINGMSGRT_FIELD_NUMBER;
        hash = (53 * hash) + getStringMsgRt().hashCode();
        break;
      case 2002:
        hash = (37 * hash) + NUMBERMSGRT_FIELD_NUMBER;
        hash = (53 * hash) + getNumberMsgRt().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.matrix.game.proto.c2s.GameResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.matrix.game.proto.c2s.GameResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.matrix.game.proto.c2s.GameResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.matrix.game.proto.c2s.GameResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.matrix.game.proto.c2s.GameResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.matrix.game.proto.c2s.GameResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.matrix.game.proto.c2s.GameResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.matrix.game.proto.c2s.GameResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.matrix.game.proto.c2s.GameResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.matrix.game.proto.c2s.GameResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.matrix.game.proto.c2s.GameResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.matrix.game.proto.c2s.GameResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.matrix.game.proto.c2s.GameResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GameResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GameResp)
      org.matrix.game.proto.c2s.GameRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.matrix.game.proto.c2s.C2SMsg.internal_static_GameResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.matrix.game.proto.c2s.C2SMsg.internal_static_GameResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.matrix.game.proto.c2s.GameResp.class, org.matrix.game.proto.c2s.GameResp.Builder.class);
    }

    // Construct using org.matrix.game.proto.c2s.GameResp.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      code_ = 0;
      if (enterGameRtBuilder_ != null) {
        enterGameRtBuilder_.clear();
      }
      if (stringMsgRtBuilder_ != null) {
        stringMsgRtBuilder_.clear();
      }
      if (numberMsgRtBuilder_ != null) {
        numberMsgRtBuilder_.clear();
      }
      payloadCase_ = 0;
      payload_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.matrix.game.proto.c2s.C2SMsg.internal_static_GameResp_descriptor;
    }

    @java.lang.Override
    public org.matrix.game.proto.c2s.GameResp getDefaultInstanceForType() {
      return org.matrix.game.proto.c2s.GameResp.getDefaultInstance();
    }

    @java.lang.Override
    public org.matrix.game.proto.c2s.GameResp build() {
      org.matrix.game.proto.c2s.GameResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.matrix.game.proto.c2s.GameResp buildPartial() {
      org.matrix.game.proto.c2s.GameResp result = new org.matrix.game.proto.c2s.GameResp(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(org.matrix.game.proto.c2s.GameResp result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.code_ = code_;
      }
    }

    private void buildPartialOneofs(org.matrix.game.proto.c2s.GameResp result) {
      result.payloadCase_ = payloadCase_;
      result.payload_ = this.payload_;
      if (payloadCase_ == 1001 &&
          enterGameRtBuilder_ != null) {
        result.payload_ = enterGameRtBuilder_.build();
      }
      if (payloadCase_ == 2001 &&
          stringMsgRtBuilder_ != null) {
        result.payload_ = stringMsgRtBuilder_.build();
      }
      if (payloadCase_ == 2002 &&
          numberMsgRtBuilder_ != null) {
        result.payload_ = numberMsgRtBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.matrix.game.proto.c2s.GameResp) {
        return mergeFrom((org.matrix.game.proto.c2s.GameResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.matrix.game.proto.c2s.GameResp other) {
      if (other == org.matrix.game.proto.c2s.GameResp.getDefaultInstance()) return this;
      if (other.getCode() != 0) {
        setCode(other.getCode());
      }
      switch (other.getPayloadCase()) {
        case ENTERGAMERT: {
          mergeEnterGameRt(other.getEnterGameRt());
          break;
        }
        case STRINGMSGRT: {
          mergeStringMsgRt(other.getStringMsgRt());
          break;
        }
        case NUMBERMSGRT: {
          mergeNumberMsgRt(other.getNumberMsgRt());
          break;
        }
        case PAYLOAD_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              code_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 8010: {
              input.readMessage(
                  getEnterGameRtFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 1001;
              break;
            } // case 8010
            case 16010: {
              input.readMessage(
                  getStringMsgRtFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 2001;
              break;
            } // case 16010
            case 16018: {
              input.readMessage(
                  getNumberMsgRtFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 2002;
              break;
            } // case 16018
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public PayloadCase
        getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public Builder clearPayload() {
      payloadCase_ = 0;
      payload_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private int code_ ;
    /**
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }
    /**
     * <code>int32 code = 1;</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(int value) {

      code_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 code = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      bitField0_ = (bitField0_ & ~0x00000001);
      code_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.game.proto.c2s.EnterGameRt, org.matrix.game.proto.c2s.EnterGameRt.Builder, org.matrix.game.proto.c2s.EnterGameRtOrBuilder> enterGameRtBuilder_;
    /**
     * <pre>
     * 登录
     * </pre>
     *
     * <code>.EnterGameRt enterGameRt = 1001;</code>
     * @return Whether the enterGameRt field is set.
     */
    @java.lang.Override
    public boolean hasEnterGameRt() {
      return payloadCase_ == 1001;
    }
    /**
     * <pre>
     * 登录
     * </pre>
     *
     * <code>.EnterGameRt enterGameRt = 1001;</code>
     * @return The enterGameRt.
     */
    @java.lang.Override
    public org.matrix.game.proto.c2s.EnterGameRt getEnterGameRt() {
      if (enterGameRtBuilder_ == null) {
        if (payloadCase_ == 1001) {
          return (org.matrix.game.proto.c2s.EnterGameRt) payload_;
        }
        return org.matrix.game.proto.c2s.EnterGameRt.getDefaultInstance();
      } else {
        if (payloadCase_ == 1001) {
          return enterGameRtBuilder_.getMessage();
        }
        return org.matrix.game.proto.c2s.EnterGameRt.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 登录
     * </pre>
     *
     * <code>.EnterGameRt enterGameRt = 1001;</code>
     */
    public Builder setEnterGameRt(org.matrix.game.proto.c2s.EnterGameRt value) {
      if (enterGameRtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        enterGameRtBuilder_.setMessage(value);
      }
      payloadCase_ = 1001;
      return this;
    }
    /**
     * <pre>
     * 登录
     * </pre>
     *
     * <code>.EnterGameRt enterGameRt = 1001;</code>
     */
    public Builder setEnterGameRt(
        org.matrix.game.proto.c2s.EnterGameRt.Builder builderForValue) {
      if (enterGameRtBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        enterGameRtBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 1001;
      return this;
    }
    /**
     * <pre>
     * 登录
     * </pre>
     *
     * <code>.EnterGameRt enterGameRt = 1001;</code>
     */
    public Builder mergeEnterGameRt(org.matrix.game.proto.c2s.EnterGameRt value) {
      if (enterGameRtBuilder_ == null) {
        if (payloadCase_ == 1001 &&
            payload_ != org.matrix.game.proto.c2s.EnterGameRt.getDefaultInstance()) {
          payload_ = org.matrix.game.proto.c2s.EnterGameRt.newBuilder((org.matrix.game.proto.c2s.EnterGameRt) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 1001) {
          enterGameRtBuilder_.mergeFrom(value);
        } else {
          enterGameRtBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 1001;
      return this;
    }
    /**
     * <pre>
     * 登录
     * </pre>
     *
     * <code>.EnterGameRt enterGameRt = 1001;</code>
     */
    public Builder clearEnterGameRt() {
      if (enterGameRtBuilder_ == null) {
        if (payloadCase_ == 1001) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 1001) {
          payloadCase_ = 0;
          payload_ = null;
        }
        enterGameRtBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 登录
     * </pre>
     *
     * <code>.EnterGameRt enterGameRt = 1001;</code>
     */
    public org.matrix.game.proto.c2s.EnterGameRt.Builder getEnterGameRtBuilder() {
      return getEnterGameRtFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 登录
     * </pre>
     *
     * <code>.EnterGameRt enterGameRt = 1001;</code>
     */
    @java.lang.Override
    public org.matrix.game.proto.c2s.EnterGameRtOrBuilder getEnterGameRtOrBuilder() {
      if ((payloadCase_ == 1001) && (enterGameRtBuilder_ != null)) {
        return enterGameRtBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 1001) {
          return (org.matrix.game.proto.c2s.EnterGameRt) payload_;
        }
        return org.matrix.game.proto.c2s.EnterGameRt.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 登录
     * </pre>
     *
     * <code>.EnterGameRt enterGameRt = 1001;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.game.proto.c2s.EnterGameRt, org.matrix.game.proto.c2s.EnterGameRt.Builder, org.matrix.game.proto.c2s.EnterGameRtOrBuilder> 
        getEnterGameRtFieldBuilder() {
      if (enterGameRtBuilder_ == null) {
        if (!(payloadCase_ == 1001)) {
          payload_ = org.matrix.game.proto.c2s.EnterGameRt.getDefaultInstance();
        }
        enterGameRtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.matrix.game.proto.c2s.EnterGameRt, org.matrix.game.proto.c2s.EnterGameRt.Builder, org.matrix.game.proto.c2s.EnterGameRtOrBuilder>(
                (org.matrix.game.proto.c2s.EnterGameRt) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 1001;
      onChanged();
      return enterGameRtBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.game.proto.c2s.StringMsgRt, org.matrix.game.proto.c2s.StringMsgRt.Builder, org.matrix.game.proto.c2s.StringMsgRtOrBuilder> stringMsgRtBuilder_;
    /**
     * <pre>
     * 测试
     * </pre>
     *
     * <code>.StringMsgRt stringMsgRt = 2001;</code>
     * @return Whether the stringMsgRt field is set.
     */
    @java.lang.Override
    public boolean hasStringMsgRt() {
      return payloadCase_ == 2001;
    }
    /**
     * <pre>
     * 测试
     * </pre>
     *
     * <code>.StringMsgRt stringMsgRt = 2001;</code>
     * @return The stringMsgRt.
     */
    @java.lang.Override
    public org.matrix.game.proto.c2s.StringMsgRt getStringMsgRt() {
      if (stringMsgRtBuilder_ == null) {
        if (payloadCase_ == 2001) {
          return (org.matrix.game.proto.c2s.StringMsgRt) payload_;
        }
        return org.matrix.game.proto.c2s.StringMsgRt.getDefaultInstance();
      } else {
        if (payloadCase_ == 2001) {
          return stringMsgRtBuilder_.getMessage();
        }
        return org.matrix.game.proto.c2s.StringMsgRt.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 测试
     * </pre>
     *
     * <code>.StringMsgRt stringMsgRt = 2001;</code>
     */
    public Builder setStringMsgRt(org.matrix.game.proto.c2s.StringMsgRt value) {
      if (stringMsgRtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        stringMsgRtBuilder_.setMessage(value);
      }
      payloadCase_ = 2001;
      return this;
    }
    /**
     * <pre>
     * 测试
     * </pre>
     *
     * <code>.StringMsgRt stringMsgRt = 2001;</code>
     */
    public Builder setStringMsgRt(
        org.matrix.game.proto.c2s.StringMsgRt.Builder builderForValue) {
      if (stringMsgRtBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        stringMsgRtBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 2001;
      return this;
    }
    /**
     * <pre>
     * 测试
     * </pre>
     *
     * <code>.StringMsgRt stringMsgRt = 2001;</code>
     */
    public Builder mergeStringMsgRt(org.matrix.game.proto.c2s.StringMsgRt value) {
      if (stringMsgRtBuilder_ == null) {
        if (payloadCase_ == 2001 &&
            payload_ != org.matrix.game.proto.c2s.StringMsgRt.getDefaultInstance()) {
          payload_ = org.matrix.game.proto.c2s.StringMsgRt.newBuilder((org.matrix.game.proto.c2s.StringMsgRt) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 2001) {
          stringMsgRtBuilder_.mergeFrom(value);
        } else {
          stringMsgRtBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 2001;
      return this;
    }
    /**
     * <pre>
     * 测试
     * </pre>
     *
     * <code>.StringMsgRt stringMsgRt = 2001;</code>
     */
    public Builder clearStringMsgRt() {
      if (stringMsgRtBuilder_ == null) {
        if (payloadCase_ == 2001) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 2001) {
          payloadCase_ = 0;
          payload_ = null;
        }
        stringMsgRtBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 测试
     * </pre>
     *
     * <code>.StringMsgRt stringMsgRt = 2001;</code>
     */
    public org.matrix.game.proto.c2s.StringMsgRt.Builder getStringMsgRtBuilder() {
      return getStringMsgRtFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 测试
     * </pre>
     *
     * <code>.StringMsgRt stringMsgRt = 2001;</code>
     */
    @java.lang.Override
    public org.matrix.game.proto.c2s.StringMsgRtOrBuilder getStringMsgRtOrBuilder() {
      if ((payloadCase_ == 2001) && (stringMsgRtBuilder_ != null)) {
        return stringMsgRtBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 2001) {
          return (org.matrix.game.proto.c2s.StringMsgRt) payload_;
        }
        return org.matrix.game.proto.c2s.StringMsgRt.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 测试
     * </pre>
     *
     * <code>.StringMsgRt stringMsgRt = 2001;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.game.proto.c2s.StringMsgRt, org.matrix.game.proto.c2s.StringMsgRt.Builder, org.matrix.game.proto.c2s.StringMsgRtOrBuilder> 
        getStringMsgRtFieldBuilder() {
      if (stringMsgRtBuilder_ == null) {
        if (!(payloadCase_ == 2001)) {
          payload_ = org.matrix.game.proto.c2s.StringMsgRt.getDefaultInstance();
        }
        stringMsgRtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.matrix.game.proto.c2s.StringMsgRt, org.matrix.game.proto.c2s.StringMsgRt.Builder, org.matrix.game.proto.c2s.StringMsgRtOrBuilder>(
                (org.matrix.game.proto.c2s.StringMsgRt) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 2001;
      onChanged();
      return stringMsgRtBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.game.proto.c2s.NumberMsgRt, org.matrix.game.proto.c2s.NumberMsgRt.Builder, org.matrix.game.proto.c2s.NumberMsgRtOrBuilder> numberMsgRtBuilder_;
    /**
     * <code>.NumberMsgRt numberMsgRt = 2002;</code>
     * @return Whether the numberMsgRt field is set.
     */
    @java.lang.Override
    public boolean hasNumberMsgRt() {
      return payloadCase_ == 2002;
    }
    /**
     * <code>.NumberMsgRt numberMsgRt = 2002;</code>
     * @return The numberMsgRt.
     */
    @java.lang.Override
    public org.matrix.game.proto.c2s.NumberMsgRt getNumberMsgRt() {
      if (numberMsgRtBuilder_ == null) {
        if (payloadCase_ == 2002) {
          return (org.matrix.game.proto.c2s.NumberMsgRt) payload_;
        }
        return org.matrix.game.proto.c2s.NumberMsgRt.getDefaultInstance();
      } else {
        if (payloadCase_ == 2002) {
          return numberMsgRtBuilder_.getMessage();
        }
        return org.matrix.game.proto.c2s.NumberMsgRt.getDefaultInstance();
      }
    }
    /**
     * <code>.NumberMsgRt numberMsgRt = 2002;</code>
     */
    public Builder setNumberMsgRt(org.matrix.game.proto.c2s.NumberMsgRt value) {
      if (numberMsgRtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        numberMsgRtBuilder_.setMessage(value);
      }
      payloadCase_ = 2002;
      return this;
    }
    /**
     * <code>.NumberMsgRt numberMsgRt = 2002;</code>
     */
    public Builder setNumberMsgRt(
        org.matrix.game.proto.c2s.NumberMsgRt.Builder builderForValue) {
      if (numberMsgRtBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        numberMsgRtBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 2002;
      return this;
    }
    /**
     * <code>.NumberMsgRt numberMsgRt = 2002;</code>
     */
    public Builder mergeNumberMsgRt(org.matrix.game.proto.c2s.NumberMsgRt value) {
      if (numberMsgRtBuilder_ == null) {
        if (payloadCase_ == 2002 &&
            payload_ != org.matrix.game.proto.c2s.NumberMsgRt.getDefaultInstance()) {
          payload_ = org.matrix.game.proto.c2s.NumberMsgRt.newBuilder((org.matrix.game.proto.c2s.NumberMsgRt) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 2002) {
          numberMsgRtBuilder_.mergeFrom(value);
        } else {
          numberMsgRtBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 2002;
      return this;
    }
    /**
     * <code>.NumberMsgRt numberMsgRt = 2002;</code>
     */
    public Builder clearNumberMsgRt() {
      if (numberMsgRtBuilder_ == null) {
        if (payloadCase_ == 2002) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 2002) {
          payloadCase_ = 0;
          payload_ = null;
        }
        numberMsgRtBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.NumberMsgRt numberMsgRt = 2002;</code>
     */
    public org.matrix.game.proto.c2s.NumberMsgRt.Builder getNumberMsgRtBuilder() {
      return getNumberMsgRtFieldBuilder().getBuilder();
    }
    /**
     * <code>.NumberMsgRt numberMsgRt = 2002;</code>
     */
    @java.lang.Override
    public org.matrix.game.proto.c2s.NumberMsgRtOrBuilder getNumberMsgRtOrBuilder() {
      if ((payloadCase_ == 2002) && (numberMsgRtBuilder_ != null)) {
        return numberMsgRtBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 2002) {
          return (org.matrix.game.proto.c2s.NumberMsgRt) payload_;
        }
        return org.matrix.game.proto.c2s.NumberMsgRt.getDefaultInstance();
      }
    }
    /**
     * <code>.NumberMsgRt numberMsgRt = 2002;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.game.proto.c2s.NumberMsgRt, org.matrix.game.proto.c2s.NumberMsgRt.Builder, org.matrix.game.proto.c2s.NumberMsgRtOrBuilder> 
        getNumberMsgRtFieldBuilder() {
      if (numberMsgRtBuilder_ == null) {
        if (!(payloadCase_ == 2002)) {
          payload_ = org.matrix.game.proto.c2s.NumberMsgRt.getDefaultInstance();
        }
        numberMsgRtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.matrix.game.proto.c2s.NumberMsgRt, org.matrix.game.proto.c2s.NumberMsgRt.Builder, org.matrix.game.proto.c2s.NumberMsgRtOrBuilder>(
                (org.matrix.game.proto.c2s.NumberMsgRt) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 2002;
      onChanged();
      return numberMsgRtBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GameResp)
  }

  // @@protoc_insertion_point(class_scope:GameResp)
  private static final org.matrix.game.proto.c2s.GameResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.matrix.game.proto.c2s.GameResp();
  }

  public static org.matrix.game.proto.c2s.GameResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GameResp>
      PARSER = new com.google.protobuf.AbstractParser<GameResp>() {
    @java.lang.Override
    public GameResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GameResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GameResp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.matrix.game.proto.c2s.GameResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

