// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

// Protobuf Java Version: 3.25.1
package org.matrix.game.proto.c2s;

public interface GameRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GameResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.TestRt testRt = 1;</code>
   * @return Whether the testRt field is set.
   */
  boolean hasTestRt();
  /**
   * <code>.TestRt testRt = 1;</code>
   * @return The testRt.
   */
  org.matrix.game.proto.c2s.TestRt getTestRt();
  /**
   * <code>.TestRt testRt = 1;</code>
   */
  org.matrix.game.proto.c2s.TestRtOrBuilder getTestRtOrBuilder();

  org.matrix.game.proto.c2s.GameResp.PayloadCase getPayloadCase();
}
