// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

// Protobuf Java Version: 3.25.1
package org.matrix.game.proto.c2s;

public interface GameReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GameReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 登录
   * </pre>
   *
   * <code>.EnterGame enterGame = 1001;</code>
   * @return Whether the enterGame field is set.
   */
  boolean hasEnterGame();
  /**
   * <pre>
   * 登录
   * </pre>
   *
   * <code>.EnterGame enterGame = 1001;</code>
   * @return The enterGame.
   */
  org.matrix.game.proto.c2s.EnterGame getEnterGame();
  /**
   * <pre>
   * 登录
   * </pre>
   *
   * <code>.EnterGame enterGame = 1001;</code>
   */
  org.matrix.game.proto.c2s.EnterGameOrBuilder getEnterGameOrBuilder();

  /**
   * <pre>
   * 测试
   * </pre>
   *
   * <code>.StringMsg stringMsg = 2001;</code>
   * @return Whether the stringMsg field is set.
   */
  boolean hasStringMsg();
  /**
   * <pre>
   * 测试
   * </pre>
   *
   * <code>.StringMsg stringMsg = 2001;</code>
   * @return The stringMsg.
   */
  org.matrix.game.proto.c2s.StringMsg getStringMsg();
  /**
   * <pre>
   * 测试
   * </pre>
   *
   * <code>.StringMsg stringMsg = 2001;</code>
   */
  org.matrix.game.proto.c2s.StringMsgOrBuilder getStringMsgOrBuilder();

  /**
   * <code>.NumberMsg numberMsg = 2002;</code>
   * @return Whether the numberMsg field is set.
   */
  boolean hasNumberMsg();
  /**
   * <code>.NumberMsg numberMsg = 2002;</code>
   * @return The numberMsg.
   */
  org.matrix.game.proto.c2s.NumberMsg getNumberMsg();
  /**
   * <code>.NumberMsg numberMsg = 2002;</code>
   */
  org.matrix.game.proto.c2s.NumberMsgOrBuilder getNumberMsgOrBuilder();

  org.matrix.game.proto.c2s.GameReq.PayloadCase getPayloadCase();
}
