// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

// Protobuf Java Version: 3.25.1
package org.matrix.game.proto.c2s;

/**
 * Protobuf type {@code GameReq}
 */
public final class GameReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GameReq)
    GameReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GameReq.newBuilder() to construct.
  private GameReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GameReq() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GameReq();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.matrix.game.proto.c2s.C2SMsg.internal_static_GameReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.matrix.game.proto.c2s.C2SMsg.internal_static_GameReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.matrix.game.proto.c2s.GameReq.class, org.matrix.game.proto.c2s.GameReq.Builder.class);
  }

  private int payloadCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object payload_;
  public enum PayloadCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    ENTERGAME(1001),
    STRINGMSG(2001),
    NUMBERMSG(2002),
    PAYLOAD_NOT_SET(0);
    private final int value;
    private PayloadCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PayloadCase valueOf(int value) {
      return forNumber(value);
    }

    public static PayloadCase forNumber(int value) {
      switch (value) {
        case 1001: return ENTERGAME;
        case 2001: return STRINGMSG;
        case 2002: return NUMBERMSG;
        case 0: return PAYLOAD_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PayloadCase
  getPayloadCase() {
    return PayloadCase.forNumber(
        payloadCase_);
  }

  public static final int ENTERGAME_FIELD_NUMBER = 1001;
  /**
   * <pre>
   * 登录
   * </pre>
   *
   * <code>.EnterGame enterGame = 1001;</code>
   * @return Whether the enterGame field is set.
   */
  @java.lang.Override
  public boolean hasEnterGame() {
    return payloadCase_ == 1001;
  }
  /**
   * <pre>
   * 登录
   * </pre>
   *
   * <code>.EnterGame enterGame = 1001;</code>
   * @return The enterGame.
   */
  @java.lang.Override
  public org.matrix.game.proto.c2s.EnterGame getEnterGame() {
    if (payloadCase_ == 1001) {
       return (org.matrix.game.proto.c2s.EnterGame) payload_;
    }
    return org.matrix.game.proto.c2s.EnterGame.getDefaultInstance();
  }
  /**
   * <pre>
   * 登录
   * </pre>
   *
   * <code>.EnterGame enterGame = 1001;</code>
   */
  @java.lang.Override
  public org.matrix.game.proto.c2s.EnterGameOrBuilder getEnterGameOrBuilder() {
    if (payloadCase_ == 1001) {
       return (org.matrix.game.proto.c2s.EnterGame) payload_;
    }
    return org.matrix.game.proto.c2s.EnterGame.getDefaultInstance();
  }

  public static final int STRINGMSG_FIELD_NUMBER = 2001;
  /**
   * <pre>
   * 测试
   * </pre>
   *
   * <code>.StringMsg stringMsg = 2001;</code>
   * @return Whether the stringMsg field is set.
   */
  @java.lang.Override
  public boolean hasStringMsg() {
    return payloadCase_ == 2001;
  }
  /**
   * <pre>
   * 测试
   * </pre>
   *
   * <code>.StringMsg stringMsg = 2001;</code>
   * @return The stringMsg.
   */
  @java.lang.Override
  public org.matrix.game.proto.c2s.StringMsg getStringMsg() {
    if (payloadCase_ == 2001) {
       return (org.matrix.game.proto.c2s.StringMsg) payload_;
    }
    return org.matrix.game.proto.c2s.StringMsg.getDefaultInstance();
  }
  /**
   * <pre>
   * 测试
   * </pre>
   *
   * <code>.StringMsg stringMsg = 2001;</code>
   */
  @java.lang.Override
  public org.matrix.game.proto.c2s.StringMsgOrBuilder getStringMsgOrBuilder() {
    if (payloadCase_ == 2001) {
       return (org.matrix.game.proto.c2s.StringMsg) payload_;
    }
    return org.matrix.game.proto.c2s.StringMsg.getDefaultInstance();
  }

  public static final int NUMBERMSG_FIELD_NUMBER = 2002;
  /**
   * <code>.NumberMsg numberMsg = 2002;</code>
   * @return Whether the numberMsg field is set.
   */
  @java.lang.Override
  public boolean hasNumberMsg() {
    return payloadCase_ == 2002;
  }
  /**
   * <code>.NumberMsg numberMsg = 2002;</code>
   * @return The numberMsg.
   */
  @java.lang.Override
  public org.matrix.game.proto.c2s.NumberMsg getNumberMsg() {
    if (payloadCase_ == 2002) {
       return (org.matrix.game.proto.c2s.NumberMsg) payload_;
    }
    return org.matrix.game.proto.c2s.NumberMsg.getDefaultInstance();
  }
  /**
   * <code>.NumberMsg numberMsg = 2002;</code>
   */
  @java.lang.Override
  public org.matrix.game.proto.c2s.NumberMsgOrBuilder getNumberMsgOrBuilder() {
    if (payloadCase_ == 2002) {
       return (org.matrix.game.proto.c2s.NumberMsg) payload_;
    }
    return org.matrix.game.proto.c2s.NumberMsg.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (payloadCase_ == 1001) {
      output.writeMessage(1001, (org.matrix.game.proto.c2s.EnterGame) payload_);
    }
    if (payloadCase_ == 2001) {
      output.writeMessage(2001, (org.matrix.game.proto.c2s.StringMsg) payload_);
    }
    if (payloadCase_ == 2002) {
      output.writeMessage(2002, (org.matrix.game.proto.c2s.NumberMsg) payload_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (payloadCase_ == 1001) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1001, (org.matrix.game.proto.c2s.EnterGame) payload_);
    }
    if (payloadCase_ == 2001) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2001, (org.matrix.game.proto.c2s.StringMsg) payload_);
    }
    if (payloadCase_ == 2002) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2002, (org.matrix.game.proto.c2s.NumberMsg) payload_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.matrix.game.proto.c2s.GameReq)) {
      return super.equals(obj);
    }
    org.matrix.game.proto.c2s.GameReq other = (org.matrix.game.proto.c2s.GameReq) obj;

    if (!getPayloadCase().equals(other.getPayloadCase())) return false;
    switch (payloadCase_) {
      case 1001:
        if (!getEnterGame()
            .equals(other.getEnterGame())) return false;
        break;
      case 2001:
        if (!getStringMsg()
            .equals(other.getStringMsg())) return false;
        break;
      case 2002:
        if (!getNumberMsg()
            .equals(other.getNumberMsg())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (payloadCase_) {
      case 1001:
        hash = (37 * hash) + ENTERGAME_FIELD_NUMBER;
        hash = (53 * hash) + getEnterGame().hashCode();
        break;
      case 2001:
        hash = (37 * hash) + STRINGMSG_FIELD_NUMBER;
        hash = (53 * hash) + getStringMsg().hashCode();
        break;
      case 2002:
        hash = (37 * hash) + NUMBERMSG_FIELD_NUMBER;
        hash = (53 * hash) + getNumberMsg().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.matrix.game.proto.c2s.GameReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.matrix.game.proto.c2s.GameReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.matrix.game.proto.c2s.GameReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.matrix.game.proto.c2s.GameReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.matrix.game.proto.c2s.GameReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.matrix.game.proto.c2s.GameReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.matrix.game.proto.c2s.GameReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.matrix.game.proto.c2s.GameReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.matrix.game.proto.c2s.GameReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.matrix.game.proto.c2s.GameReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.matrix.game.proto.c2s.GameReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.matrix.game.proto.c2s.GameReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.matrix.game.proto.c2s.GameReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GameReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GameReq)
      org.matrix.game.proto.c2s.GameReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.matrix.game.proto.c2s.C2SMsg.internal_static_GameReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.matrix.game.proto.c2s.C2SMsg.internal_static_GameReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.matrix.game.proto.c2s.GameReq.class, org.matrix.game.proto.c2s.GameReq.Builder.class);
    }

    // Construct using org.matrix.game.proto.c2s.GameReq.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (enterGameBuilder_ != null) {
        enterGameBuilder_.clear();
      }
      if (stringMsgBuilder_ != null) {
        stringMsgBuilder_.clear();
      }
      if (numberMsgBuilder_ != null) {
        numberMsgBuilder_.clear();
      }
      payloadCase_ = 0;
      payload_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.matrix.game.proto.c2s.C2SMsg.internal_static_GameReq_descriptor;
    }

    @java.lang.Override
    public org.matrix.game.proto.c2s.GameReq getDefaultInstanceForType() {
      return org.matrix.game.proto.c2s.GameReq.getDefaultInstance();
    }

    @java.lang.Override
    public org.matrix.game.proto.c2s.GameReq build() {
      org.matrix.game.proto.c2s.GameReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.matrix.game.proto.c2s.GameReq buildPartial() {
      org.matrix.game.proto.c2s.GameReq result = new org.matrix.game.proto.c2s.GameReq(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(org.matrix.game.proto.c2s.GameReq result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(org.matrix.game.proto.c2s.GameReq result) {
      result.payloadCase_ = payloadCase_;
      result.payload_ = this.payload_;
      if (payloadCase_ == 1001 &&
          enterGameBuilder_ != null) {
        result.payload_ = enterGameBuilder_.build();
      }
      if (payloadCase_ == 2001 &&
          stringMsgBuilder_ != null) {
        result.payload_ = stringMsgBuilder_.build();
      }
      if (payloadCase_ == 2002 &&
          numberMsgBuilder_ != null) {
        result.payload_ = numberMsgBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.matrix.game.proto.c2s.GameReq) {
        return mergeFrom((org.matrix.game.proto.c2s.GameReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.matrix.game.proto.c2s.GameReq other) {
      if (other == org.matrix.game.proto.c2s.GameReq.getDefaultInstance()) return this;
      switch (other.getPayloadCase()) {
        case ENTERGAME: {
          mergeEnterGame(other.getEnterGame());
          break;
        }
        case STRINGMSG: {
          mergeStringMsg(other.getStringMsg());
          break;
        }
        case NUMBERMSG: {
          mergeNumberMsg(other.getNumberMsg());
          break;
        }
        case PAYLOAD_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8010: {
              input.readMessage(
                  getEnterGameFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 1001;
              break;
            } // case 8010
            case 16010: {
              input.readMessage(
                  getStringMsgFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 2001;
              break;
            } // case 16010
            case 16018: {
              input.readMessage(
                  getNumberMsgFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 2002;
              break;
            } // case 16018
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public PayloadCase
        getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public Builder clearPayload() {
      payloadCase_ = 0;
      payload_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.game.proto.c2s.EnterGame, org.matrix.game.proto.c2s.EnterGame.Builder, org.matrix.game.proto.c2s.EnterGameOrBuilder> enterGameBuilder_;
    /**
     * <pre>
     * 登录
     * </pre>
     *
     * <code>.EnterGame enterGame = 1001;</code>
     * @return Whether the enterGame field is set.
     */
    @java.lang.Override
    public boolean hasEnterGame() {
      return payloadCase_ == 1001;
    }
    /**
     * <pre>
     * 登录
     * </pre>
     *
     * <code>.EnterGame enterGame = 1001;</code>
     * @return The enterGame.
     */
    @java.lang.Override
    public org.matrix.game.proto.c2s.EnterGame getEnterGame() {
      if (enterGameBuilder_ == null) {
        if (payloadCase_ == 1001) {
          return (org.matrix.game.proto.c2s.EnterGame) payload_;
        }
        return org.matrix.game.proto.c2s.EnterGame.getDefaultInstance();
      } else {
        if (payloadCase_ == 1001) {
          return enterGameBuilder_.getMessage();
        }
        return org.matrix.game.proto.c2s.EnterGame.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 登录
     * </pre>
     *
     * <code>.EnterGame enterGame = 1001;</code>
     */
    public Builder setEnterGame(org.matrix.game.proto.c2s.EnterGame value) {
      if (enterGameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        enterGameBuilder_.setMessage(value);
      }
      payloadCase_ = 1001;
      return this;
    }
    /**
     * <pre>
     * 登录
     * </pre>
     *
     * <code>.EnterGame enterGame = 1001;</code>
     */
    public Builder setEnterGame(
        org.matrix.game.proto.c2s.EnterGame.Builder builderForValue) {
      if (enterGameBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        enterGameBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 1001;
      return this;
    }
    /**
     * <pre>
     * 登录
     * </pre>
     *
     * <code>.EnterGame enterGame = 1001;</code>
     */
    public Builder mergeEnterGame(org.matrix.game.proto.c2s.EnterGame value) {
      if (enterGameBuilder_ == null) {
        if (payloadCase_ == 1001 &&
            payload_ != org.matrix.game.proto.c2s.EnterGame.getDefaultInstance()) {
          payload_ = org.matrix.game.proto.c2s.EnterGame.newBuilder((org.matrix.game.proto.c2s.EnterGame) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 1001) {
          enterGameBuilder_.mergeFrom(value);
        } else {
          enterGameBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 1001;
      return this;
    }
    /**
     * <pre>
     * 登录
     * </pre>
     *
     * <code>.EnterGame enterGame = 1001;</code>
     */
    public Builder clearEnterGame() {
      if (enterGameBuilder_ == null) {
        if (payloadCase_ == 1001) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 1001) {
          payloadCase_ = 0;
          payload_ = null;
        }
        enterGameBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 登录
     * </pre>
     *
     * <code>.EnterGame enterGame = 1001;</code>
     */
    public org.matrix.game.proto.c2s.EnterGame.Builder getEnterGameBuilder() {
      return getEnterGameFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 登录
     * </pre>
     *
     * <code>.EnterGame enterGame = 1001;</code>
     */
    @java.lang.Override
    public org.matrix.game.proto.c2s.EnterGameOrBuilder getEnterGameOrBuilder() {
      if ((payloadCase_ == 1001) && (enterGameBuilder_ != null)) {
        return enterGameBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 1001) {
          return (org.matrix.game.proto.c2s.EnterGame) payload_;
        }
        return org.matrix.game.proto.c2s.EnterGame.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 登录
     * </pre>
     *
     * <code>.EnterGame enterGame = 1001;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.game.proto.c2s.EnterGame, org.matrix.game.proto.c2s.EnterGame.Builder, org.matrix.game.proto.c2s.EnterGameOrBuilder> 
        getEnterGameFieldBuilder() {
      if (enterGameBuilder_ == null) {
        if (!(payloadCase_ == 1001)) {
          payload_ = org.matrix.game.proto.c2s.EnterGame.getDefaultInstance();
        }
        enterGameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.matrix.game.proto.c2s.EnterGame, org.matrix.game.proto.c2s.EnterGame.Builder, org.matrix.game.proto.c2s.EnterGameOrBuilder>(
                (org.matrix.game.proto.c2s.EnterGame) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 1001;
      onChanged();
      return enterGameBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.game.proto.c2s.StringMsg, org.matrix.game.proto.c2s.StringMsg.Builder, org.matrix.game.proto.c2s.StringMsgOrBuilder> stringMsgBuilder_;
    /**
     * <pre>
     * 测试
     * </pre>
     *
     * <code>.StringMsg stringMsg = 2001;</code>
     * @return Whether the stringMsg field is set.
     */
    @java.lang.Override
    public boolean hasStringMsg() {
      return payloadCase_ == 2001;
    }
    /**
     * <pre>
     * 测试
     * </pre>
     *
     * <code>.StringMsg stringMsg = 2001;</code>
     * @return The stringMsg.
     */
    @java.lang.Override
    public org.matrix.game.proto.c2s.StringMsg getStringMsg() {
      if (stringMsgBuilder_ == null) {
        if (payloadCase_ == 2001) {
          return (org.matrix.game.proto.c2s.StringMsg) payload_;
        }
        return org.matrix.game.proto.c2s.StringMsg.getDefaultInstance();
      } else {
        if (payloadCase_ == 2001) {
          return stringMsgBuilder_.getMessage();
        }
        return org.matrix.game.proto.c2s.StringMsg.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 测试
     * </pre>
     *
     * <code>.StringMsg stringMsg = 2001;</code>
     */
    public Builder setStringMsg(org.matrix.game.proto.c2s.StringMsg value) {
      if (stringMsgBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        stringMsgBuilder_.setMessage(value);
      }
      payloadCase_ = 2001;
      return this;
    }
    /**
     * <pre>
     * 测试
     * </pre>
     *
     * <code>.StringMsg stringMsg = 2001;</code>
     */
    public Builder setStringMsg(
        org.matrix.game.proto.c2s.StringMsg.Builder builderForValue) {
      if (stringMsgBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        stringMsgBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 2001;
      return this;
    }
    /**
     * <pre>
     * 测试
     * </pre>
     *
     * <code>.StringMsg stringMsg = 2001;</code>
     */
    public Builder mergeStringMsg(org.matrix.game.proto.c2s.StringMsg value) {
      if (stringMsgBuilder_ == null) {
        if (payloadCase_ == 2001 &&
            payload_ != org.matrix.game.proto.c2s.StringMsg.getDefaultInstance()) {
          payload_ = org.matrix.game.proto.c2s.StringMsg.newBuilder((org.matrix.game.proto.c2s.StringMsg) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 2001) {
          stringMsgBuilder_.mergeFrom(value);
        } else {
          stringMsgBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 2001;
      return this;
    }
    /**
     * <pre>
     * 测试
     * </pre>
     *
     * <code>.StringMsg stringMsg = 2001;</code>
     */
    public Builder clearStringMsg() {
      if (stringMsgBuilder_ == null) {
        if (payloadCase_ == 2001) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 2001) {
          payloadCase_ = 0;
          payload_ = null;
        }
        stringMsgBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 测试
     * </pre>
     *
     * <code>.StringMsg stringMsg = 2001;</code>
     */
    public org.matrix.game.proto.c2s.StringMsg.Builder getStringMsgBuilder() {
      return getStringMsgFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 测试
     * </pre>
     *
     * <code>.StringMsg stringMsg = 2001;</code>
     */
    @java.lang.Override
    public org.matrix.game.proto.c2s.StringMsgOrBuilder getStringMsgOrBuilder() {
      if ((payloadCase_ == 2001) && (stringMsgBuilder_ != null)) {
        return stringMsgBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 2001) {
          return (org.matrix.game.proto.c2s.StringMsg) payload_;
        }
        return org.matrix.game.proto.c2s.StringMsg.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 测试
     * </pre>
     *
     * <code>.StringMsg stringMsg = 2001;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.game.proto.c2s.StringMsg, org.matrix.game.proto.c2s.StringMsg.Builder, org.matrix.game.proto.c2s.StringMsgOrBuilder> 
        getStringMsgFieldBuilder() {
      if (stringMsgBuilder_ == null) {
        if (!(payloadCase_ == 2001)) {
          payload_ = org.matrix.game.proto.c2s.StringMsg.getDefaultInstance();
        }
        stringMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.matrix.game.proto.c2s.StringMsg, org.matrix.game.proto.c2s.StringMsg.Builder, org.matrix.game.proto.c2s.StringMsgOrBuilder>(
                (org.matrix.game.proto.c2s.StringMsg) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 2001;
      onChanged();
      return stringMsgBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.game.proto.c2s.NumberMsg, org.matrix.game.proto.c2s.NumberMsg.Builder, org.matrix.game.proto.c2s.NumberMsgOrBuilder> numberMsgBuilder_;
    /**
     * <code>.NumberMsg numberMsg = 2002;</code>
     * @return Whether the numberMsg field is set.
     */
    @java.lang.Override
    public boolean hasNumberMsg() {
      return payloadCase_ == 2002;
    }
    /**
     * <code>.NumberMsg numberMsg = 2002;</code>
     * @return The numberMsg.
     */
    @java.lang.Override
    public org.matrix.game.proto.c2s.NumberMsg getNumberMsg() {
      if (numberMsgBuilder_ == null) {
        if (payloadCase_ == 2002) {
          return (org.matrix.game.proto.c2s.NumberMsg) payload_;
        }
        return org.matrix.game.proto.c2s.NumberMsg.getDefaultInstance();
      } else {
        if (payloadCase_ == 2002) {
          return numberMsgBuilder_.getMessage();
        }
        return org.matrix.game.proto.c2s.NumberMsg.getDefaultInstance();
      }
    }
    /**
     * <code>.NumberMsg numberMsg = 2002;</code>
     */
    public Builder setNumberMsg(org.matrix.game.proto.c2s.NumberMsg value) {
      if (numberMsgBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        numberMsgBuilder_.setMessage(value);
      }
      payloadCase_ = 2002;
      return this;
    }
    /**
     * <code>.NumberMsg numberMsg = 2002;</code>
     */
    public Builder setNumberMsg(
        org.matrix.game.proto.c2s.NumberMsg.Builder builderForValue) {
      if (numberMsgBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        numberMsgBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 2002;
      return this;
    }
    /**
     * <code>.NumberMsg numberMsg = 2002;</code>
     */
    public Builder mergeNumberMsg(org.matrix.game.proto.c2s.NumberMsg value) {
      if (numberMsgBuilder_ == null) {
        if (payloadCase_ == 2002 &&
            payload_ != org.matrix.game.proto.c2s.NumberMsg.getDefaultInstance()) {
          payload_ = org.matrix.game.proto.c2s.NumberMsg.newBuilder((org.matrix.game.proto.c2s.NumberMsg) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 2002) {
          numberMsgBuilder_.mergeFrom(value);
        } else {
          numberMsgBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 2002;
      return this;
    }
    /**
     * <code>.NumberMsg numberMsg = 2002;</code>
     */
    public Builder clearNumberMsg() {
      if (numberMsgBuilder_ == null) {
        if (payloadCase_ == 2002) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 2002) {
          payloadCase_ = 0;
          payload_ = null;
        }
        numberMsgBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.NumberMsg numberMsg = 2002;</code>
     */
    public org.matrix.game.proto.c2s.NumberMsg.Builder getNumberMsgBuilder() {
      return getNumberMsgFieldBuilder().getBuilder();
    }
    /**
     * <code>.NumberMsg numberMsg = 2002;</code>
     */
    @java.lang.Override
    public org.matrix.game.proto.c2s.NumberMsgOrBuilder getNumberMsgOrBuilder() {
      if ((payloadCase_ == 2002) && (numberMsgBuilder_ != null)) {
        return numberMsgBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 2002) {
          return (org.matrix.game.proto.c2s.NumberMsg) payload_;
        }
        return org.matrix.game.proto.c2s.NumberMsg.getDefaultInstance();
      }
    }
    /**
     * <code>.NumberMsg numberMsg = 2002;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.game.proto.c2s.NumberMsg, org.matrix.game.proto.c2s.NumberMsg.Builder, org.matrix.game.proto.c2s.NumberMsgOrBuilder> 
        getNumberMsgFieldBuilder() {
      if (numberMsgBuilder_ == null) {
        if (!(payloadCase_ == 2002)) {
          payload_ = org.matrix.game.proto.c2s.NumberMsg.getDefaultInstance();
        }
        numberMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.matrix.game.proto.c2s.NumberMsg, org.matrix.game.proto.c2s.NumberMsg.Builder, org.matrix.game.proto.c2s.NumberMsgOrBuilder>(
                (org.matrix.game.proto.c2s.NumberMsg) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 2002;
      onChanged();
      return numberMsgBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GameReq)
  }

  // @@protoc_insertion_point(class_scope:GameReq)
  private static final org.matrix.game.proto.c2s.GameReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.matrix.game.proto.c2s.GameReq();
  }

  public static org.matrix.game.proto.c2s.GameReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GameReq>
      PARSER = new com.google.protobuf.AbstractParser<GameReq>() {
    @java.lang.Override
    public GameReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GameReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GameReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.matrix.game.proto.c2s.GameReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

