// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

// Protobuf Java Version: 3.25.1
package org.matrix.game.proto.c2s;

public interface NumberMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NumberMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 playerId = 1;</code>
   * @return The playerId.
   */
  long getPlayerId();

  /**
   * <code>int32 count = 2;</code>
   * @return The count.
   */
  int getCount();
}
