// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

// Protobuf Java Version: 3.25.1
package org.matrix.game.proto.c2s;

public interface StringMsgRtOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StringMsgRt)
    com.google.protobuf.MessageOrBuilder {
}
