// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

// Protobuf Java Version: 3.25.1
package org.matrix.game.proto.c2s;

public interface Test2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:Test2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *Message类的一个属性，属性名称是id，序号为1
   * </pre>
   *
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <pre>
   *Message类的一个属性，属性名称是content，序号为2
   * </pre>
   *
   * <code>string content = 2;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   *Message类的一个属性，属性名称是content，序号为2
   * </pre>
   *
   * <code>string content = 2;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
