// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package org.matrix.game.proto;

public interface HelloMatrixOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloMatrix)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *Message类的一个属性，属性名称是id，序号为1
   * </pre>
   *
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <pre>
   *Message类的一个属性，属性名称是content，序号为2
   * </pre>
   *
   * <code>string content = 2;</code>
   */
  java.lang.String getContent();
  /**
   * <pre>
   *Message类的一个属性，属性名称是content，序号为2
   * </pre>
   *
   * <code>string content = 2;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
