// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

// Protobuf Java Version: 3.25.1
package org.matrix.game.proto;

/**
 * Protobuf type {@code HelloMatrixRt}
 */
public final class HelloMatrixRt extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:HelloMatrixRt)
    HelloMatrixRtOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HelloMatrixRt.newBuilder() to construct.
  private HelloMatrixRt(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HelloMatrixRt() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HelloMatrixRt();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.matrix.game.proto.TestMessage.internal_static_HelloMatrixRt_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.matrix.game.proto.TestMessage.internal_static_HelloMatrixRt_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.matrix.game.proto.HelloMatrixRt.class, org.matrix.game.proto.HelloMatrixRt.Builder.class);
  }

  private int payloadCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object payload_;
  public enum PayloadCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    TESTRT(1),
    PAYLOAD_NOT_SET(0);
    private final int value;
    private PayloadCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PayloadCase valueOf(int value) {
      return forNumber(value);
    }

    public static PayloadCase forNumber(int value) {
      switch (value) {
        case 1: return TESTRT;
        case 0: return PAYLOAD_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PayloadCase
  getPayloadCase() {
    return PayloadCase.forNumber(
        payloadCase_);
  }

  public static final int TESTRT_FIELD_NUMBER = 1;
  /**
   * <code>.TestRt testRt = 1;</code>
   * @return Whether the testRt field is set.
   */
  @java.lang.Override
  public boolean hasTestRt() {
    return payloadCase_ == 1;
  }
  /**
   * <code>.TestRt testRt = 1;</code>
   * @return The testRt.
   */
  @java.lang.Override
  public org.matrix.game.proto.TestRt getTestRt() {
    if (payloadCase_ == 1) {
       return (org.matrix.game.proto.TestRt) payload_;
    }
    return org.matrix.game.proto.TestRt.getDefaultInstance();
  }
  /**
   * <code>.TestRt testRt = 1;</code>
   */
  @java.lang.Override
  public org.matrix.game.proto.TestRtOrBuilder getTestRtOrBuilder() {
    if (payloadCase_ == 1) {
       return (org.matrix.game.proto.TestRt) payload_;
    }
    return org.matrix.game.proto.TestRt.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (payloadCase_ == 1) {
      output.writeMessage(1, (org.matrix.game.proto.TestRt) payload_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (payloadCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (org.matrix.game.proto.TestRt) payload_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.matrix.game.proto.HelloMatrixRt)) {
      return super.equals(obj);
    }
    org.matrix.game.proto.HelloMatrixRt other = (org.matrix.game.proto.HelloMatrixRt) obj;

    if (!getPayloadCase().equals(other.getPayloadCase())) return false;
    switch (payloadCase_) {
      case 1:
        if (!getTestRt()
            .equals(other.getTestRt())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (payloadCase_) {
      case 1:
        hash = (37 * hash) + TESTRT_FIELD_NUMBER;
        hash = (53 * hash) + getTestRt().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.matrix.game.proto.HelloMatrixRt parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.matrix.game.proto.HelloMatrixRt parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.matrix.game.proto.HelloMatrixRt parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.matrix.game.proto.HelloMatrixRt parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.matrix.game.proto.HelloMatrixRt parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.matrix.game.proto.HelloMatrixRt parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.matrix.game.proto.HelloMatrixRt parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.matrix.game.proto.HelloMatrixRt parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.matrix.game.proto.HelloMatrixRt parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.matrix.game.proto.HelloMatrixRt parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.matrix.game.proto.HelloMatrixRt parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.matrix.game.proto.HelloMatrixRt parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.matrix.game.proto.HelloMatrixRt prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code HelloMatrixRt}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:HelloMatrixRt)
      org.matrix.game.proto.HelloMatrixRtOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.matrix.game.proto.TestMessage.internal_static_HelloMatrixRt_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.matrix.game.proto.TestMessage.internal_static_HelloMatrixRt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.matrix.game.proto.HelloMatrixRt.class, org.matrix.game.proto.HelloMatrixRt.Builder.class);
    }

    // Construct using org.matrix.game.proto.HelloMatrixRt.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (testRtBuilder_ != null) {
        testRtBuilder_.clear();
      }
      payloadCase_ = 0;
      payload_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.matrix.game.proto.TestMessage.internal_static_HelloMatrixRt_descriptor;
    }

    @java.lang.Override
    public org.matrix.game.proto.HelloMatrixRt getDefaultInstanceForType() {
      return org.matrix.game.proto.HelloMatrixRt.getDefaultInstance();
    }

    @java.lang.Override
    public org.matrix.game.proto.HelloMatrixRt build() {
      org.matrix.game.proto.HelloMatrixRt result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.matrix.game.proto.HelloMatrixRt buildPartial() {
      org.matrix.game.proto.HelloMatrixRt result = new org.matrix.game.proto.HelloMatrixRt(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(org.matrix.game.proto.HelloMatrixRt result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(org.matrix.game.proto.HelloMatrixRt result) {
      result.payloadCase_ = payloadCase_;
      result.payload_ = this.payload_;
      if (payloadCase_ == 1 &&
          testRtBuilder_ != null) {
        result.payload_ = testRtBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.matrix.game.proto.HelloMatrixRt) {
        return mergeFrom((org.matrix.game.proto.HelloMatrixRt)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.matrix.game.proto.HelloMatrixRt other) {
      if (other == org.matrix.game.proto.HelloMatrixRt.getDefaultInstance()) return this;
      switch (other.getPayloadCase()) {
        case TESTRT: {
          mergeTestRt(other.getTestRt());
          break;
        }
        case PAYLOAD_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getTestRtFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 1;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public PayloadCase
        getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public Builder clearPayload() {
      payloadCase_ = 0;
      payload_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.game.proto.TestRt, org.matrix.game.proto.TestRt.Builder, org.matrix.game.proto.TestRtOrBuilder> testRtBuilder_;
    /**
     * <code>.TestRt testRt = 1;</code>
     * @return Whether the testRt field is set.
     */
    @java.lang.Override
    public boolean hasTestRt() {
      return payloadCase_ == 1;
    }
    /**
     * <code>.TestRt testRt = 1;</code>
     * @return The testRt.
     */
    @java.lang.Override
    public org.matrix.game.proto.TestRt getTestRt() {
      if (testRtBuilder_ == null) {
        if (payloadCase_ == 1) {
          return (org.matrix.game.proto.TestRt) payload_;
        }
        return org.matrix.game.proto.TestRt.getDefaultInstance();
      } else {
        if (payloadCase_ == 1) {
          return testRtBuilder_.getMessage();
        }
        return org.matrix.game.proto.TestRt.getDefaultInstance();
      }
    }
    /**
     * <code>.TestRt testRt = 1;</code>
     */
    public Builder setTestRt(org.matrix.game.proto.TestRt value) {
      if (testRtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        testRtBuilder_.setMessage(value);
      }
      payloadCase_ = 1;
      return this;
    }
    /**
     * <code>.TestRt testRt = 1;</code>
     */
    public Builder setTestRt(
        org.matrix.game.proto.TestRt.Builder builderForValue) {
      if (testRtBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        testRtBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 1;
      return this;
    }
    /**
     * <code>.TestRt testRt = 1;</code>
     */
    public Builder mergeTestRt(org.matrix.game.proto.TestRt value) {
      if (testRtBuilder_ == null) {
        if (payloadCase_ == 1 &&
            payload_ != org.matrix.game.proto.TestRt.getDefaultInstance()) {
          payload_ = org.matrix.game.proto.TestRt.newBuilder((org.matrix.game.proto.TestRt) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 1) {
          testRtBuilder_.mergeFrom(value);
        } else {
          testRtBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 1;
      return this;
    }
    /**
     * <code>.TestRt testRt = 1;</code>
     */
    public Builder clearTestRt() {
      if (testRtBuilder_ == null) {
        if (payloadCase_ == 1) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 1) {
          payloadCase_ = 0;
          payload_ = null;
        }
        testRtBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.TestRt testRt = 1;</code>
     */
    public org.matrix.game.proto.TestRt.Builder getTestRtBuilder() {
      return getTestRtFieldBuilder().getBuilder();
    }
    /**
     * <code>.TestRt testRt = 1;</code>
     */
    @java.lang.Override
    public org.matrix.game.proto.TestRtOrBuilder getTestRtOrBuilder() {
      if ((payloadCase_ == 1) && (testRtBuilder_ != null)) {
        return testRtBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 1) {
          return (org.matrix.game.proto.TestRt) payload_;
        }
        return org.matrix.game.proto.TestRt.getDefaultInstance();
      }
    }
    /**
     * <code>.TestRt testRt = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.matrix.game.proto.TestRt, org.matrix.game.proto.TestRt.Builder, org.matrix.game.proto.TestRtOrBuilder> 
        getTestRtFieldBuilder() {
      if (testRtBuilder_ == null) {
        if (!(payloadCase_ == 1)) {
          payload_ = org.matrix.game.proto.TestRt.getDefaultInstance();
        }
        testRtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.matrix.game.proto.TestRt, org.matrix.game.proto.TestRt.Builder, org.matrix.game.proto.TestRtOrBuilder>(
                (org.matrix.game.proto.TestRt) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 1;
      onChanged();
      return testRtBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:HelloMatrixRt)
  }

  // @@protoc_insertion_point(class_scope:HelloMatrixRt)
  private static final org.matrix.game.proto.HelloMatrixRt DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.matrix.game.proto.HelloMatrixRt();
  }

  public static org.matrix.game.proto.HelloMatrixRt getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HelloMatrixRt>
      PARSER = new com.google.protobuf.AbstractParser<HelloMatrixRt>() {
    @java.lang.Override
    public HelloMatrixRt parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<HelloMatrixRt> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HelloMatrixRt> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.matrix.game.proto.HelloMatrixRt getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

