// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

// Protobuf Java Version: 3.25.1
package org.matrix.game.proto;

public final class TestMessage {
  private TestMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloMatrix_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloMatrix_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloMatrixRt_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloMatrixRt_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Test_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Test_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TestRt_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TestRt_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Test2_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Test2_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Test2Rt_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Test2Rt_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\"H\n\013HelloMatrix\022\025\n\004test\030\003 \001(" +
      "\0132\005.TestH\000\022\027\n\005test2\030\004 \001(\0132\006.Test2H\000B\t\n\007p" +
      "ayload\"5\n\rHelloMatrixRt\022\031\n\006testRt\030\001 \001(\0132" +
      "\007.TestRtH\000B\t\n\007payload\"#\n\004Test\022\n\n\002id\030\001 \001(" +
      "\005\022\017\n\007content\030\002 \001(\t\"%\n\006TestRt\022\n\n\002id\030\001 \001(\005" +
      "\022\017\n\007content\030\002 \001(\t\"$\n\005Test2\022\n\n\002id\030\001 \001(\005\022\017" +
      "\n\007content\030\002 \001(\t\"&\n\007Test2Rt\022\n\n\002id\030\001 \001(\005\022\017" +
      "\n\007content\030\002 \001(\tB&\n\025org.matrix.game.proto" +
      "B\013TestMessageP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_HelloMatrix_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HelloMatrix_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloMatrix_descriptor,
        new java.lang.String[] { "Test", "Test2", "Payload", });
    internal_static_HelloMatrixRt_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HelloMatrixRt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloMatrixRt_descriptor,
        new java.lang.String[] { "TestRt", "Payload", });
    internal_static_Test_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Test_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Test_descriptor,
        new java.lang.String[] { "Id", "Content", });
    internal_static_TestRt_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_TestRt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TestRt_descriptor,
        new java.lang.String[] { "Id", "Content", });
    internal_static_Test2_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Test2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Test2_descriptor,
        new java.lang.String[] { "Id", "Content", });
    internal_static_Test2Rt_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Test2Rt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Test2Rt_descriptor,
        new java.lang.String[] { "Id", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
